---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "3qqUsIsdu7BDkxktSsqdXZ5XHDPPYGhRCpdZfRBMzjJGXfXesMQlWGV\
      Rx9ksrti9+5worxQFFvIfxI86YquTcoj04oEkwJgOdZ3Va/FmniYcR5GL1LTb8Ij\
      W+TlT06RI+qgg6i+R8cuS9MHzVKUSFQlpv3kMPavaHloWNGVpY/8Oyp8V33CrXTZ\
      sShXJpUY95ppT7Njn1bkXqSaymg/8iJZtGQ8NuQAJCPiAscZW6JasB78aTql0PVJ\
      HnQjR99dAwwEkomrtKum++1jD8AZ2JBA0Rc9LhBkpyJpJoeI/DNiS+xQsN43GCzB\
      k0naJLKJZDLURyyVfWAvSr95+Ix01V+GHMbG4A7nSrHW/vvLLuW2GR1QXgMkzAXa\
      XyvWNzC1+JU1TEfLknCo87QjnK6VEwgRycr2BahPpyHuQj9pkzNMYHRDj+lKW7bd\
      Z3Pxz/pwxKwkFkXigvJuDzxK5wk1atTI1itd88Ne9kkr4YIN0og2jYVQATsaT7Ub\
      0nDxAWf8//llA1BXu851QkfeLNikMvcWXr0v/int9npcyxA+xImJ9kD1G0nw6Pg+\
      +ilRla4k0+TZg53YJ1z4Zg/bDdM8MyNZYTfltTm0ULpB6KSuRyleLLDrIlpHYg7N\
      suVwxfnTHwgwRCewKoC4PoohgtGgIdxMMh4EFSqtZXMV2Jejv490="
    # AWS_SECRET_ACCESS_KEY
    - secure: "S86Ue+FqWGte4KPLcCq/lZrpXpvZbEct3B50GDs1t29i3FEo80JdtCJ\
      CwLgTbxEYB0P9h9pGXhLv/IzN+Myxum/fkRpKDTMdWJcqhlgMqVLad6h6xfk1o74\
      skk6mEt3hwGUHtHriaxwrMvSYpaqsExBUIxY+vdyjUbL6HrhbjmlhO6D8OOl4PS4\
      fbMtDyDXARSlx66fb4KDF3h2mRD9dkdHk4BDXadaLbkiz6RXim8KvRr3NHNnHfgq\
      ZxbENCgTHOClHL49NV1ShcLRq9H6HEFXaOZWakHBmwEp+ui9YntwR1UreJPi505z\
      rgCTZua9LYMMspYxqJFzfRGgW4+O6hvNBTE100tJyQ4QOYvtec9lNIj7NE/cb5fT\
      LGm+Vhf4T98hHZO9pn77AyH+r2PpwK9s0DuwTuvYWWi3MtlgoxJ1WaTBG7Cce9WV\
      BzE65TISKG9g9LWqbVp/I4L1m/4zfvonu6NewM7e438RoE37uvuVDIPzQvgT72ja\
      ZP/qzJXMGDz8I/WxIgiKkjpqCWnWcWaB5084+oNLGzvx6PJsEdez59gIsJ/pOUdE\
      PNhWHK+NsV1ddhAfR+vZBke/l+c/T7HF21HaFMuLxo4YEDD4fOYHHqfSd9TGdDjf\
      zVveB6pv8DCRmwtJzEPVIqaKfi3xxOzagDXYOwxfxS4/yEM6ujto="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
