---
# tasks file for cyhy_archive

- name: Create the /var/cyhy/scripts directory
  ansible.builtin.file:
    mode: 0755
    path: /var/cyhy/scripts
    state: directory

- name: Download cyhy_archive.sh from the cisagov/cyhy-core repository
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/cisagov/cyhy-core/develop/var/cyhy_archive.sh
    dest: /var/cyhy/scripts/cyhy_archive.sh
    mode: 0755
