---
- name: Install cisagov/cyhy-core
  ansible.builtin.include_role:
    name: cyhy_core
  vars:
    cyhy_core_maxmind_license_key: "{{ cyhy_archive_maxmind_license_key }}"

- name: Create the /var/cyhy/scripts directory
  ansible.builtin.file:
    group: "{{ cyhy_archive_file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ cyhy_archive_file_owner_username | default(omit) }}"
    path: /var/cyhy/scripts
    state: directory

- name: Download cyhy_archive.sh from the cisagov/cyhy-core repository
  ansible.builtin.get_url:
    dest: /var/cyhy/scripts/cyhy_archive.sh
    group: "{{ cyhy_archive_file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ cyhy_archive_file_owner_username | default(omit) }}"
    url: https://raw.githubusercontent.com/cisagov/cyhy-core/develop/var/cyhy_archive.sh
