---
- name: Install cisagov/cyhy-core
  ansible.builtin.include_role:
    name: cyhy_core
  vars:
    cyhy_core_install_geoipupdate: "{{ cyhy_archive_install_geoipupdate }}"
    cyhy_core_maxmind_account_id: "{{ cyhy_archive_maxmind_account_id }}"
    cyhy_core_maxmind_license_key: "{{ cyhy_archive_maxmind_license_key }}"

- name: Create the /var/cyhy/scripts directory
  ansible.builtin.file:
    group: "{{ cyhy_archive_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_archive_file_owner_username | default(omit) }}"
    path: /var/cyhy/scripts
    state: directory

- name: Download cyhy_archive.sh from the cisagov/cyhy-core repository
  ansible.builtin.get_url:
    dest: /var/cyhy/scripts/cyhy_archive.sh
    group: "{{ cyhy_archive_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_archive_file_owner_username | default(omit) }}"
    url: >-
      https://raw.githubusercontent.com/cisagov/cyhy-core/{{
      cyhy_archive_cyhy_core_version }}/var/cyhy_archive.sh
